# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shainer's Site
email: shainer@chakralinux.org
description: > # this means to ignore newlines until "baseurl:"
  Random stuff I find interesting or I am working on. At some point I will
  move all the content from my old website, giudoku.sourceforge.net, here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shainer.github.io" # the base hostname & protocol for your site
github_username:  shainer
google_analytics: "UA-92679498-1"

# Build settings
markdown: kramdown
